from datetime import datetime
import pytz
from tkinter import *
import time

root = Tk()
root.title('World Clock')
root.geometry("600x600")

def times():
#India
    home = pytz.timezone("Asia/kolkata")
    local_time = datetime.now(home)
    current_time = local_time.strftime("%H:%M:%S")
    clock.config(text=current_time)
    name.config(text="India")
#America
    home1 = pytz.timezone("America/New_York")
    local_time1 = datetime.now(home1)
    current_time1 = local_time1.strftime("%H:%M:%S")
    clock1.config(text=current_time1)
    name1.config(text="America")
#London
    home2 = pytz.timezone("europe/london")
    local_time2 = datetime.now(home2)
    current_time2 = local_time2.strftime("%H:%M:%S")
    clock2.config(text=current_time2)
    name2.config(text="London")
#Japan
    home3 = pytz.timezone("Asia/Tokyo")
    local_time3 = datetime.now(home3)
    current_time3 = local_time3.strftime("%H:%M:%S")
    clock3.config(text=current_time3)
    name3.config(text="Japan")
#Africa
    home4 = pytz.timezone("Africa/cairo")
    local_time4 = datetime.now(home4)
    current_time4 = local_time4.strftime("%H:%M:%S")
    clock4.config(text=current_time4)
    name4.config(text="Africa")
#Australia
    home5 = pytz.timezone("Australia/Sydney")
    local_time5 = datetime.now(home5)
    current_time5 = local_time5.strftime("%H:%M:%S")
    clock5.config(text=current_time5)
    name5.config(text="Australia")
#South Korea
    home6 = pytz.timezone("Asia/Seoul")
    local_time6 = datetime.now(home6)
    current_time6 = local_time6.strftime("%H:%M:%S")
    clock6.config(text=current_time6)
    name6.config(text="South Korea")
#Canada 
    home7 = pytz.timezone("Canada/Atlantic")
    local_time7 = datetime.now(home7)
    current_time7 = local_time7.strftime("%H:%M:%S")
    clock7.config(text=current_time7)
    name7.config(text="Canada")
#Singapore
    home8 = pytz.timezone("Singapore")
    local_time8 = datetime.now(home8)
    current_time8 = local_time8.strftime("%H:%M:%S")
    clock8.config(text=current_time8)
    name8.config(text="Singapore")
#Dubai
    home9 = pytz.timezone("Asia/Qatar")
    local_time9 = datetime.now(home9)
    current_time9 = local_time9.strftime("%H:%M:%S")
    clock9.config(text=current_time9)
    name9.config(text="Dubai")
#France
    home10 = pytz.timezone("Europe/Paris")
    local_time10 = datetime.now(home10)
    current_time10 = local_time10.strftime("%H:%M:%S")
    clock10.config(text=current_time10)
    name10.config(text="France")
#Mexico
    home11 = pytz.timezone("Mexico/General")
    local_time11 = datetime.now(home11)
    current_time11 = local_time11.strftime("%H:%M:%S")
    clock11.config(text=current_time11)
    name11.config(text="Mexico")
#turkey
    home12 = pytz.timezone("Turkey")
    local_time12 = datetime.now(home12)
    current_time12 = local_time12.strftime("%H:%M:%S")
    clock12.config(text=current_time12)
    name12.config(text="Turkey")
#Iran
    home13 = pytz.timezone("Iran")
    local_time13 = datetime.now(home13)
    current_time13 = local_time13.strftime("%H:%M:%S")
    clock13.config(text=current_time13)
    name13.config(text="Iran")
#Israel
    home14 = pytz.timezone("Israel")
    local_time14 = datetime.now(home14)
    current_time14 = local_time14.strftime("%H:%M:%S")
    clock14.config(text=current_time14)
    name14.config(text="Israel")
#Hawaii
    home15 = pytz.timezone("US/Hawaii")
    local_time15 = datetime.now(home15)
    current_time15 = local_time15.strftime("%H:%M:%S")
    clock15.config(text=current_time15)
    name15.config(text="Hawaii")
#Portugal
    home16 = pytz.timezone("Portugal")
    local_time16 = datetime.now(home16)
    current_time16 = local_time16.strftime("%H:%M:%S")
    clock16.config(text=current_time16)
    name16.config(text="Portugal")
#Hongkong
    home17 = pytz.timezone("Hongkong")
    local_time17 = datetime.now(home17)
    current_time17 = local_time17.strftime("%H:%M:%S")
    clock17.config(text=current_time17)
    name17.config(text="Hongkong")
#Egypt
    home18 = pytz.timezone("Egypt")
    local_time18 = datetime.now(home18)
    current_time18 = local_time18.strftime("%H:%M:%S")
    clock18.config(text=current_time18)
    name18.config(text="Egypt")
#Iceland
    home19 = pytz.timezone("Iceland")
    local_time19 = datetime.now(home19)
    current_time19 = local_time19.strftime("%H:%M:%S")
    clock19.config(text=current_time19)
    name19.config(text="Iceland")

    

#styling
#India
name = Label(root, font = ("times", 20, "bold"))
name.place(x=40,y=5)
clock = Label(root, font = ("times", 25, "bold"))
clock.place(x=10,y=40)
nota = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota.place(x=10,y=80)
#America
name1 = Label(root, font = ("times", 20, "bold"))
name1.place(x=330,y=5)
clock1 = Label(root, font = ("times", 25, "bold"))
clock1.place(x=310,y=40)
nota1 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota1.place(x=310,y=80)
#London
name2 = Label(root, font = ("times", 20, "bold"))
name2.place(x=40,y=205)
clock2 = Label(root, font = ("times", 25, "bold"))
clock2.place(x=10,y=240)
nota2 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota2.place(x=10,y=280)
#Japan
name3 = Label(root, font = ("times", 20, "bold"))
name3.place(x=330,y=205)
clock3 = Label(root, font = ("times", 25, "bold"))
clock3.place(x=310,y=240)
nota3 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota3.place(x=310,y=280)
#Africa
name4 = Label(root, font = ("times", 20, "bold"))
name4.place(x=630,y=5)
clock4 = Label(root, font = ("times", 25, "bold"))
clock4.place(x=610,y=40)
nota4 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota4.place(x=610,y=80)
#Australia
name5 = Label(root, font = ("times", 20, "bold"))
name5.place(x=630,y=205)
clock5 = Label(root, font = ("times", 25, "bold"))
clock5.place(x=610,y=240)
nota5 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota5.place(x=610,y=280)
#South Korea
name6 = Label(root, font = ("times", 20, "bold"))
name6.place(x=910,y=5)
clock6 = Label(root, font = ("times", 25, "bold"))
clock6.place(x=910,y=40)
nota6 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota6.place(x=910,y=80)
#Canada
name7 = Label(root, font = ("times", 20, "bold"))
name7.place(x=930,y=205)
clock7 = Label(root, font = ("times", 25, "bold"))
clock7.place(x=910,y=240)
nota7 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota7.place(x=910,y=280)
#Singapore
name8 = Label(root, font = ("times", 20, "bold"))
name8.place(x=1225,y=5)
clock8 = Label(root, font = ("times", 25, "bold"))
clock8.place(x=1210,y=40)
nota8 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota8.place(x=1210,y=80)
#Dubai
name9 = Label(root, font = ("times", 20, "bold"))
name9.place(x=1230,y=205)
clock9 = Label(root, font = ("times", 25, "bold"))
clock9.place(x=1210,y=240)
nota9 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota9.place(x=1210,y=280)
#France
name10 = Label(root, font = ("times", 20, "bold"))
name10.place(x=40,y=405)
clock10 = Label(root, font = ("times", 25, "bold"))
clock10.place(x=10,y=440)
nota10 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota10.place(x=10,y=480)
#Mexico
name11 = Label(root, font = ("times", 20, "bold"))
name11.place(x=340,y=405)
clock11 = Label(root, font = ("times", 25, "bold"))
clock11.place(x=310,y=440)
nota11 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota11.place(x=310,y=480)
#Turkey
name12 = Label(root, font = ("times", 20, "bold"))
name12.place(x=640,y=405)
clock12 = Label(root, font = ("times", 25, "bold"))
clock12.place(x=610,y=440)
nota12 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota12.place(x=610,y=480)
#Iran
name13 = Label(root, font = ("times", 20, "bold"))
name13.place(x=940,y=405)
clock13 = Label(root, font = ("times", 25, "bold"))
clock13.place(x=910,y=440)
nota13 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota13.place(x=910,y=480)
#Israel
name14 = Label(root, font = ("times", 20, "bold"))
name14.place(x=1240,y=405)
clock14 = Label(root, font = ("times", 25, "bold"))
clock14.place(x=1210,y=440)
nota14 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota14.place(x=1210,y=480)
#Hawaii
name15 = Label(root, font = ("times", 20, "bold"))
name15.place(x=30,y=605)
clock15 = Label(root, font = ("times", 25, "bold"))
clock15.place(x=10,y=640)
nota15 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota15.place(x=10,y=680)
#Portugal
name16 = Label(root, font = ("times", 20, "bold"))
name16.place(x=330,y=605)
clock16 = Label(root, font = ("times", 25, "bold"))
clock16.place(x=310,y=640)
nota16 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota16.place(x=310,y=680)
#Hongkong
name17 = Label(root, font = ("times", 20, "bold"))
name17.place(x=625,y=605)
clock17 = Label(root, font = ("times", 25, "bold"))
clock17.place(x=610,y=640)
nota17 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota17.place(x=610,y=680)
#Egypt
name18 = Label(root, font = ("times", 20, "bold"))
name18.place(x=940,y=605)
clock18 = Label(root, font = ("times", 25, "bold"))
clock18.place(x=910,y=640)
nota18 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota18.place(x=910,y=680)
#Iceland
name19 = Label(root, font = ("times", 20, "bold"))
name19.place(x=1230,y=605)
clock19 = Label(root, font = ("times", 25, "bold"))
clock19.place(x=1210,y=640)
nota19 = Label(root,text = "Hours  Minutes  Seconds", font = "times 10 bold")
nota19.place(x=1210,y=680)


times()

root.mainloop()